# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1353, 734)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"    color: #ecf0f1;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"}\n"
"QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2c3e50, stop:0.5 #34495e, stop:1 #3a4f6b);\n"
"    color: #ecf0f1;\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 13px;\n"
"}\n"
"QLabel {\n"
"    font-size: 14px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addWidget(self.gridWidget, 0, 0, 1, 1)
        self.comportselectergroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.comportselectergroupBox.setGeometry(QtCore.QRect(10, 10, 721, 101))
        self.comportselectergroupBox.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #34495e, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    color: #ecf0f1;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: #ecf0f1;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"}")
        self.comportselectergroupBox.setObjectName("comportselectergroupBox")
        self.comportlabel = QtWidgets.QLabel(self.comportselectergroupBox)
        self.comportlabel.setGeometry(QtCore.QRect(40, 40, 91, 41))
        self.comportlabel.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #3a4f6b, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    padding: 12px 5px;\n"
"    font-size: 14px;\n"
"}")
        self.comportlabel.setObjectName("comportlabel")
        self.comportcomboBox = QtWidgets.QComboBox(self.comportselectergroupBox)
        self.comportcomboBox.setGeometry(QtCore.QRect(170, 40, 151, 31))
        self.comportcomboBox.setStyleSheet("QComboBox {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 6px;\n"
"    color: #ecf0f1;\n"
"    font-size: 13px;\n"
"    padding: 6px 12px;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    color: #ecf0f1;\n"
"    selection-background-color: #3498db;\n"
"}")
        self.comportcomboBox.setObjectName("comportcomboBox")
        self.comportconnectpushButton = QtWidgets.QPushButton(self.comportselectergroupBox)
        self.comportconnectpushButton.setGeometry(QtCore.QRect(360, 40, 131, 31))
        self.comportconnectpushButton.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #3498db, stop:1 #2980b9);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #52a8e0, stop:1 #3498db);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2980b9, stop:1 #1f5f8b);\n"
"}")
        self.comportconnectpushButton.setObjectName("comportconnectpushButton")
        self.comportrefreshpushButton = QtWidgets.QPushButton(self.comportselectergroupBox)
        self.comportrefreshpushButton.setGeometry(QtCore.QRect(530, 40, 111, 31))
        self.comportrefreshpushButton.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #7f8c8d, stop:1 #95a5a6);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #95a5a6, stop:1 #b2bec3);\n"
"}\n"
"")
        self.comportrefreshpushButton.setObjectName("comportrefreshpushButton")
        self.comportindicator = QtWidgets.QLabel(self.comportselectergroupBox)
        self.comportindicator.setGeometry(QtCore.QRect(10, 50, 15, 15))
        self.comportindicator.setStyleSheet("QLabel {\n"
"    background: #e74c3c;\n"
"    border-radius: 7px;\n"
"    min-width: 15px;\n"
"    max-width: 15px;\n"
"    min-height: 15px;\n"
"    max-height: 15px;\n"
"}\n"
"\n"
"QLabel#connectionStatus[connected=\"true\"] {\n"
"    background: #27ae60;\n"
"}")
        self.comportindicator.setText("")
        self.comportindicator.setObjectName("comportindicator")
        self.inkpumpgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.inkpumpgroupBox.setGeometry(QtCore.QRect(10, 120, 731, 241))
        self.inkpumpgroupBox.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #34495e, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    color: #ecf0f1;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: #ecf0f1;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"}")
        self.inkpumpgroupBox.setObjectName("inkpumpgroupBox")
        self.label_2 = QtWidgets.QLabel(self.inkpumpgroupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 72, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.inkpumpgroupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 51, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.inkpumpgroupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 61, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.inkpumpgroupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 51, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.inkpumpgroupBox)
        self.label_6.setGeometry(QtCore.QRect(80, 40, 101, 20))
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.syringersizecomboBox01 = QtWidgets.QComboBox(self.inkpumpgroupBox)
        self.syringersizecomboBox01.setGeometry(QtCore.QRect(90, 71, 76, 31))
        self.syringersizecomboBox01.setStyleSheet("QComboBox {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 6px;\n"
"    color: #ecf0f1;\n"
"    font-size: 13px;\n"
"    padding: 6px 12px;\n"
"    min-width: 50px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    color: #ecf0f1;\n"
"    selection-background-color: #3498db;\n"
"}")
        self.syringersizecomboBox01.setObjectName("syringersizecomboBox01")
        self.syringersizecomboBox02 = QtWidgets.QComboBox(self.inkpumpgroupBox)
        self.syringersizecomboBox02.setGeometry(QtCore.QRect(90, 110, 76, 31))
        self.syringersizecomboBox02.setStyleSheet("QComboBox {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 6px;\n"
"    color: #ecf0f1;\n"
"    font-size: 13px;\n"
"    padding: 6px 12px;\n"
"    min-width: 50px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    color: #ecf0f1;\n"
"    selection-background-color: #3498db;\n"
"}")
        self.syringersizecomboBox02.setObjectName("syringersizecomboBox02")
        self.syringersizecomboBox03 = QtWidgets.QComboBox(self.inkpumpgroupBox)
        self.syringersizecomboBox03.setGeometry(QtCore.QRect(90, 150, 76, 31))
        self.syringersizecomboBox03.setStyleSheet("QComboBox {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 6px;\n"
"    color: #ecf0f1;\n"
"    font-size: 13px;\n"
"    padding: 6px 12px;\n"
"    min-width: 50px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    color: #ecf0f1;\n"
"    selection-background-color: #3498db;\n"
"}")
        self.syringersizecomboBox03.setObjectName("syringersizecomboBox03")
        self.syringersizecomboBox04 = QtWidgets.QComboBox(self.inkpumpgroupBox)
        self.syringersizecomboBox04.setGeometry(QtCore.QRect(90, 190, 76, 31))
        self.syringersizecomboBox04.setStyleSheet("QComboBox {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 6px;\n"
"    color: #ecf0f1;\n"
"    font-size: 13px;\n"
"    padding: 6px 12px;\n"
"    min-width: 50px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    color: #ecf0f1;\n"
"    selection-background-color: #3498db;\n"
"}")
        self.syringersizecomboBox04.setObjectName("syringersizecomboBox04")
        self.label_7 = QtWidgets.QLabel(self.inkpumpgroupBox)
        self.label_7.setGeometry(QtCore.QRect(190, 40, 81, 21))
        self.label_7.setObjectName("label_7")
        self.flowratedoubleSpinBox01 = QtWidgets.QDoubleSpinBox(self.inkpumpgroupBox)
        self.flowratedoubleSpinBox01.setGeometry(QtCore.QRect(190, 70, 81, 31))
        self.flowratedoubleSpinBox01.setStyleSheet("QDoubleSpinBox {\n"
"    background: #2c3e50;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 4px;\n"
"    color: #ecf0f1;\n"
"    font-size: 23px;\n"
"\n"
"}\n"
"\n"
"QDoubleSpinBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"")
        self.flowratedoubleSpinBox01.setObjectName("flowratedoubleSpinBox01")
        self.flowratedoubleSpinBox02 = QtWidgets.QDoubleSpinBox(self.inkpumpgroupBox)
        self.flowratedoubleSpinBox02.setGeometry(QtCore.QRect(190, 110, 81, 31))
        self.flowratedoubleSpinBox02.setStyleSheet("QDoubleSpinBox {\n"
"    background: #2c3e50;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 4px;\n"
"    color: #ecf0f1;\n"
"    font-size: 23px;\n"
"\n"
"}\n"
"\n"
"QDoubleSpinBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"")
        self.flowratedoubleSpinBox02.setObjectName("flowratedoubleSpinBox02")
        self.flowratedoubleSpinBox03 = QtWidgets.QDoubleSpinBox(self.inkpumpgroupBox)
        self.flowratedoubleSpinBox03.setGeometry(QtCore.QRect(190, 150, 81, 31))
        self.flowratedoubleSpinBox03.setStyleSheet("QDoubleSpinBox {\n"
"    background: #2c3e50;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 4px;\n"
"    color: #ecf0f1;\n"
"    font-size: 23px;\n"
"\n"
"}\n"
"\n"
"QDoubleSpinBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"")
        self.flowratedoubleSpinBox03.setObjectName("flowratedoubleSpinBox03")
        self.flowratedoubleSpinBox04 = QtWidgets.QDoubleSpinBox(self.inkpumpgroupBox)
        self.flowratedoubleSpinBox04.setGeometry(QtCore.QRect(190, 190, 81, 31))
        self.flowratedoubleSpinBox04.setStyleSheet("QDoubleSpinBox {\n"
"    background: #2c3e50;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 4px;\n"
"    color: #ecf0f1;\n"
"    font-size: 23px;\n"
"\n"
"}\n"
"\n"
"QDoubleSpinBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"")
        self.flowratedoubleSpinBox04.setObjectName("flowratedoubleSpinBox04")
        self.inkmotorpushButton01Forward = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton01Forward.setGeometry(QtCore.QRect(320, 70, 111, 31))
        self.inkmotorpushButton01Forward.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #3498db, stop:1 #2980b9);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #52a8e0, stop:1 #3498db);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2980b9, stop:1 #1f5f8b);\n"
"}")
        self.inkmotorpushButton01Forward.setObjectName("inkmotorpushButton01Forward")
        self.inkmotorpushButton02Forward = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton02Forward.setGeometry(QtCore.QRect(320, 110, 111, 31))
        self.inkmotorpushButton02Forward.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #3498db, stop:1 #2980b9);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #52a8e0, stop:1 #3498db);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2980b9, stop:1 #1f5f8b);\n"
"}")
        self.inkmotorpushButton02Forward.setObjectName("inkmotorpushButton02Forward")
        self.inkmotorpushButton03Forward = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton03Forward.setGeometry(QtCore.QRect(320, 150, 111, 31))
        self.inkmotorpushButton03Forward.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #3498db, stop:1 #2980b9);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #52a8e0, stop:1 #3498db);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2980b9, stop:1 #1f5f8b);\n"
"}")
        self.inkmotorpushButton03Forward.setObjectName("inkmotorpushButton03Forward")
        self.inkmotorpushButton04Forward = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton04Forward.setGeometry(QtCore.QRect(320, 190, 111, 31))
        self.inkmotorpushButton04Forward.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #3498db, stop:1 #2980b9);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #52a8e0, stop:1 #3498db);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2980b9, stop:1 #1f5f8b);\n"
"}")
        self.inkmotorpushButton04Forward.setObjectName("inkmotorpushButton04Forward")
        self.inkmotorpushButton01Backward = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton01Backward.setGeometry(QtCore.QRect(460, 70, 111, 31))
        self.inkmotorpushButton01Backward.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #7f8c8d, stop:1 #95a5a6);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #95a5a6, stop:1 #b2bec3);\n"
"}\n"
"")
        self.inkmotorpushButton01Backward.setObjectName("inkmotorpushButton01Backward")
        self.inkmotorpushButton02Backward = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton02Backward.setGeometry(QtCore.QRect(460, 110, 111, 31))
        self.inkmotorpushButton02Backward.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #7f8c8d, stop:1 #95a5a6);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #95a5a6, stop:1 #b2bec3);\n"
"}\n"
"")
        self.inkmotorpushButton02Backward.setObjectName("inkmotorpushButton02Backward")
        self.inkmotorpushButton03Backward = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton03Backward.setGeometry(QtCore.QRect(460, 150, 111, 31))
        self.inkmotorpushButton03Backward.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #7f8c8d, stop:1 #95a5a6);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #95a5a6, stop:1 #b2bec3);\n"
"}\n"
"")
        self.inkmotorpushButton03Backward.setObjectName("inkmotorpushButton03Backward")
        self.inkmotorpushButton03Backward_2 = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton03Backward_2.setGeometry(QtCore.QRect(460, 190, 111, 31))
        self.inkmotorpushButton03Backward_2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #7f8c8d, stop:1 #95a5a6);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #95a5a6, stop:1 #b2bec3);\n"
"}\n"
"")
        self.inkmotorpushButton03Backward_2.setObjectName("inkmotorpushButton03Backward_2")
        self.ink01indicator = QtWidgets.QLabel(self.inkpumpgroupBox)
        self.ink01indicator.setGeometry(QtCore.QRect(10, 80, 15, 15))
        self.ink01indicator.setStyleSheet("QLabel {\n"
"    background: #e74c3c;\n"
"    border-radius: 7px;\n"
"    min-width: 15px;\n"
"    max-width: 15px;\n"
"    min-height: 15px;\n"
"    max-height: 15px;\n"
"}\n"
"\n"
"QLabel#connectionStatus[connected=\"true\"] {\n"
"    background: #27ae60;\n"
"}")
        self.ink01indicator.setText("")
        self.ink01indicator.setObjectName("ink01indicator")
        self.ink02indicator = QtWidgets.QLabel(self.inkpumpgroupBox)
        self.ink02indicator.setGeometry(QtCore.QRect(10, 120, 15, 15))
        self.ink02indicator.setStyleSheet("QLabel {\n"
"    background: #e74c3c;\n"
"    border-radius: 7px;\n"
"    min-width: 15px;\n"
"    max-width: 15px;\n"
"    min-height: 15px;\n"
"    max-height: 15px;\n"
"}\n"
"\n"
"QLabel#connectionStatus[connected=\"true\"] {\n"
"    background: #27ae60;\n"
"}")
        self.ink02indicator.setText("")
        self.ink02indicator.setObjectName("ink02indicator")
        self.ink03indicator = QtWidgets.QLabel(self.inkpumpgroupBox)
        self.ink03indicator.setGeometry(QtCore.QRect(10, 160, 15, 15))
        self.ink03indicator.setStyleSheet("QLabel {\n"
"    background: #e74c3c;\n"
"    border-radius: 7px;\n"
"    min-width: 15px;\n"
"    max-width: 15px;\n"
"    min-height: 15px;\n"
"    max-height: 15px;\n"
"}\n"
"\n"
"QLabel#connectionStatus[connected=\"true\"] {\n"
"    background: #27ae60;\n"
"}")
        self.ink03indicator.setText("")
        self.ink03indicator.setObjectName("ink03indicator")
        self.ink04indicator = QtWidgets.QLabel(self.inkpumpgroupBox)
        self.ink04indicator.setGeometry(QtCore.QRect(10, 200, 15, 15))
        self.ink04indicator.setStyleSheet("QLabel {\n"
"    background: #e74c3c;\n"
"    border-radius: 7px;\n"
"    min-width: 15px;\n"
"    max-width: 15px;\n"
"    min-height: 15px;\n"
"    max-height: 15px;\n"
"}\n"
"\n"
"QLabel#connectionStatus[connected=\"true\"] {\n"
"    background: #27ae60;\n"
"}")
        self.ink04indicator.setText("")
        self.ink04indicator.setObjectName("ink04indicator")
        self.inkmotorpushButton01Stop = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton01Stop.setGeometry(QtCore.QRect(600, 68, 101, 31))
        self.inkmotorpushButton01Stop.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #e74c3c, stop:1 #c0392b);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #ec7063, stop:1 #e74c3c);\n"
"}")
        self.inkmotorpushButton01Stop.setObjectName("inkmotorpushButton01Stop")
        self.inkmotorpushButton02Stop = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton02Stop.setGeometry(QtCore.QRect(600, 110, 101, 31))
        self.inkmotorpushButton02Stop.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #e74c3c, stop:1 #c0392b);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #ec7063, stop:1 #e74c3c);\n"
"}")
        self.inkmotorpushButton02Stop.setObjectName("inkmotorpushButton02Stop")
        self.inkmotorpushButton03Stop = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton03Stop.setGeometry(QtCore.QRect(600, 150, 101, 31))
        self.inkmotorpushButton03Stop.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #e74c3c, stop:1 #c0392b);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #ec7063, stop:1 #e74c3c);\n"
"}")
        self.inkmotorpushButton03Stop.setObjectName("inkmotorpushButton03Stop")
        self.inkmotorpushButton04Stop = QtWidgets.QPushButton(self.inkpumpgroupBox)
        self.inkmotorpushButton04Stop.setGeometry(QtCore.QRect(600, 190, 101, 31))
        self.inkmotorpushButton04Stop.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #e74c3c, stop:1 #c0392b);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #ec7063, stop:1 #e74c3c);\n"
"}")
        self.inkmotorpushButton04Stop.setObjectName("inkmotorpushButton04Stop")
        self.startpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startpushButton.setGeometry(QtCore.QRect(760, 600, 181, 51))
        self.startpushButton.setStyleSheet("QPushButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #27ae60, stop:1 #2ecc71);\n"
"    font-size: 30px;\n"
"    font-weight: 600;\n"
"    border-radius: 6px;\n"
"    min-width: 100px;\n"
"    padding: 10px 20px;\n"
"   text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2ecc71, stop:1 #58d68d);\n"
"}")
        self.startpushButton.setObjectName("startpushButton")
        self.stoppushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stoppushButton.setGeometry(QtCore.QRect(970, 600, 181, 51))
        self.stoppushButton.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #e74c3c, stop:1 #c0392b);\n"
"    font-size: 30px;\n"
"    font-weight: 600;\n"
"    min-width: 100px; \n"
"    border-radius: 6px;\n"
"    padding: 10px 20px;\n"
"   text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #ec7063, stop:1 #e74c3c);\n"
"}")
        self.stoppushButton.setObjectName("stoppushButton")
        self.movementspeedgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.movementspeedgroupBox.setGeometry(QtCore.QRect(760, 370, 381, 201))
        self.movementspeedgroupBox.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #34495e, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    color: #ecf0f1;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: #ecf0f1;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"}\n"
"")
        self.movementspeedgroupBox.setObjectName("movementspeedgroupBox")
        self.label_10 = QtWidgets.QLabel(self.movementspeedgroupBox)
        self.label_10.setGeometry(QtCore.QRect(60, 70, 111, 20))
        self.label_10.setObjectName("label_10")
        self.coaterspeedoubleSpinBox = QtWidgets.QDoubleSpinBox(self.movementspeedgroupBox)
        self.coaterspeedoubleSpinBox.setGeometry(QtCore.QRect(200, 50, 101, 61))
        self.coaterspeedoubleSpinBox.setStyleSheet("QDoubleSpinBox {\n"
"    background: #2c3e50;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 4px;\n"
"    color: #ecf0f1;\n"
"    font-size: 25px;;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"QDoubleSpinBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"\n"
"\n"
"")
        self.coaterspeedoubleSpinBox.setObjectName("coaterspeedoubleSpinBox")
        self.drivemotorforwardpushButton = QtWidgets.QPushButton(self.movementspeedgroupBox)
        self.drivemotorforwardpushButton.setGeometry(QtCore.QRect(10, 140, 101, 31))
        self.drivemotorforwardpushButton.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #3498db, stop:1 #2980b9);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #52a8e0, stop:1 #3498db);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2980b9, stop:1 #1f5f8b);\n"
"}")
        self.drivemotorforwardpushButton.setObjectName("drivemotorforwardpushButton")
        self.drivemotorbackwardpushButton = QtWidgets.QPushButton(self.movementspeedgroupBox)
        self.drivemotorbackwardpushButton.setGeometry(QtCore.QRect(120, 140, 121, 31))
        self.drivemotorbackwardpushButton.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #7f8c8d, stop:1 #95a5a6);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #95a5a6, stop:1 #b2bec3);\n"
"}\n"
"")
        self.drivemotorbackwardpushButton.setObjectName("drivemotorbackwardpushButton")
        self.drivemotorstoppushButton = QtWidgets.QPushButton(self.movementspeedgroupBox)
        self.drivemotorstoppushButton.setGeometry(QtCore.QRect(250, 140, 111, 31))
        self.drivemotorstoppushButton.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #e74c3c, stop:1 #c0392b);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #ec7063, stop:1 #e74c3c);\n"
"}")
        self.drivemotorstoppushButton.setObjectName("drivemotorstoppushButton")
        self.tempgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.tempgroupBox.setGeometry(QtCore.QRect(10, 370, 351, 201))
        self.tempgroupBox.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #34495e, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    color: #ecf0f1;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: #ecf0f1;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"}")
        self.tempgroupBox.setObjectName("tempgroupBox")
        self.label_11 = QtWidgets.QLabel(self.tempgroupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tempgroupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 150, 81, 16))
        self.label_12.setObjectName("label_12")
        self.tempdoubleSpinBox01 = QtWidgets.QDoubleSpinBox(self.tempgroupBox)
        self.tempdoubleSpinBox01.setGeometry(QtCore.QRect(90, 50, 91, 51))
        self.tempdoubleSpinBox01.setStyleSheet("QDoubleSpinBox {\n"
"    background: #2c3e50;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 4px;\n"
"    color: #ecf0f1;\n"
"    font-size: 25px;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"QDoubleSpinBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"")
        self.tempdoubleSpinBox01.setObjectName("tempdoubleSpinBox01")
        self.tempdoubleSpinBox02 = QtWidgets.QDoubleSpinBox(self.tempgroupBox)
        self.tempdoubleSpinBox02.setGeometry(QtCore.QRect(90, 130, 91, 51))
        self.tempdoubleSpinBox02.setStyleSheet("QDoubleSpinBox {\n"
"    background: #2c3e50;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 4px;\n"
"    color: #ecf0f1;\n"
"    font-size: 25px;;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"QDoubleSpinBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"")
        self.tempdoubleSpinBox02.setObjectName("tempdoubleSpinBox02")
        self.templcdNumber01 = QtWidgets.QLCDNumber(self.tempgroupBox)
        self.templcdNumber01.setGeometry(QtCore.QRect(190, 50, 121, 41))
        self.templcdNumber01.setStyleSheet("QLCDNumber {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2c3e50, stop:1 #34495e);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 6px;\n"
"    color: #ecf0f1;\n"
" \n"
"    font-weight: bold;\n"
"    padding: 12px;\n"
"    text-align: center;\n"
"}")
        self.templcdNumber01.setObjectName("templcdNumber01")
        self.templcdNumber02 = QtWidgets.QLCDNumber(self.tempgroupBox)
        self.templcdNumber02.setGeometry(QtCore.QRect(190, 130, 121, 51))
        self.templcdNumber02.setStyleSheet("QLCDNumber {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2c3e50, stop:1 #34495e);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 6px;\n"
"    color: #ecf0f1;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    padding: 12px;\n"
"    text-align: center;\n"
"}")
        self.templcdNumber02.setObjectName("templcdNumber02")
        self.label_13 = QtWidgets.QLabel(self.tempgroupBox)
        self.label_13.setGeometry(QtCore.QRect(210, 20, 91, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tempgroupBox)
        self.label_14.setGeometry(QtCore.QRect(120, 30, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tempgroupBox)
        self.label_15.setGeometry(QtCore.QRect(320, 60, 16, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tempgroupBox)
        self.label_16.setGeometry(QtCore.QRect(320, 150, 16, 16))
        self.label_16.setObjectName("label_16")
        self.livecamlabel = QtWidgets.QLabel(self.centralwidget)
        self.livecamlabel.setGeometry(QtCore.QRect(760, 20, 581, 341))
        self.livecamlabel.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #3a4f6b, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    padding: 12px 5px;\n"
"    font-size: 14px;\n"
"}")
        self.livecamlabel.setObjectName("livecamlabel")
        self.currentstategroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.currentstategroupBox.setGeometry(QtCore.QRect(10, 580, 731, 91))
        self.currentstategroupBox.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #34495e, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    color: #ecf0f1;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: #ecf0f1;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"}\n"
"")
        self.currentstategroupBox.setObjectName("currentstategroupBox")
        self.currentlabel01 = QtWidgets.QLabel(self.currentstategroupBox)
        self.currentlabel01.setGeometry(QtCore.QRect(250, 30, 161, 41))
        self.currentlabel01.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #3a4f6b, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    padding: 12px 5px;\n"
"    font-size: 14px;\n"
"}")
        self.currentlabel01.setObjectName("currentlabel01")
        self.currentlabel02 = QtWidgets.QLabel(self.currentstategroupBox)
        self.currentlabel02.setGeometry(QtCore.QRect(500, 30, 161, 41))
        self.currentlabel02.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #3a4f6b, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    padding: 12px 5px;\n"
"    font-size: 14px;\n"
"}")
        self.currentlabel02.setObjectName("currentlabel02")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(390, 380, 351, 191))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #34495e, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    color: #ecf0f1;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: #ecf0f1;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 90, 81, 21))
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setGeometry(QtCore.QRect(110, 80, 101, 51))
        self.doubleSpinBox.setStyleSheet("QDoubleSpinBox {\n"
"    background: #2c3e50;\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 4px;\n"
"    color: #ecf0f1;\n"
"    font-size: 25px;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"QDoubleSpinBox:focus {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"")
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(223, 80, 101, 51))
        self.lcdNumber.setStyleSheet("QLCDNumber {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2c3e50, stop:1 #34495e);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 6px;\n"
"    color: #ecf0f1;\n"
" \n"
"    font-weight: bold;\n"
"    padding: 12px;\n"
"    text-align: center;\n"
"}")
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(140, 40, 47, 13))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(230, 30, 101, 31))
        self.label_18.setObjectName("label_18")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1150, 369, 191, 201))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #34495e, stop:1 #2c3e50);\n"
"    border: 1px solid #4a5f7a;\n"
"    border-radius: 12px;\n"
"    color: #ecf0f1;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: #ecf0f1;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 60, 140, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #27ae60, stop:1 #2ecc71);\n"
"    font-size: 20px;\n"
"    font-weight: 600;\n"
"    border-radius: 6px;\n"
"    min-width: 100px;\n"
"    padding: 10px 20px;\n"
"   text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #2ecc71, stop:1 #58d68d);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 130, 140, 51))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #e74c3c, stop:1 #c0392b);\n"
"    font-size: 20px;\n"
"    font-weight: 600;\n"
"    min-width: 100px; \n"
"    border-radius: 6px;\n"
"    padding: 10px 20px;\n"
"   text-transform: uppercase;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                stop:0 #ec7063, stop:1 #e74c3c);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1353, 25))
        self.menubar.setStyleSheet("QMenuBar {\n"
"    background: #2c3e50;\n"
"    border-bottom: 1px solid #4a5f7a;\n"
"    color: #ecf0f1;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: #3498db;\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setStyleSheet("QMenu {\n"
"    background: #34495e;\n"
"    border: 1px solid #4a5f7a;\n"
"    color: #ecf0f1;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 5px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background: #3498db;\n"
"}")
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionAdd_Ink = QtWidgets.QAction(MainWindow)
        self.actionAdd_Ink.setObjectName("actionAdd_Ink")
        self.menuEdit.addAction(self.actionopen)
        self.menuEdit.addAction(self.actionsave)
        self.menuEdit.addAction(self.actionSave_As)
        self.menuEdit.addAction(self.actionAdd_Ink)
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comportselectergroupBox.setTitle(_translate("MainWindow", "COM Port Selecter"))
        self.comportlabel.setText(_translate("MainWindow", "COM Port :"))
        self.comportconnectpushButton.setText(_translate("MainWindow", "Connect"))
        self.comportrefreshpushButton.setText(_translate("MainWindow", "Refresh"))
        self.inkpumpgroupBox.setTitle(_translate("MainWindow", "Ink Pump Configeration"))
        self.label_2.setText(_translate("MainWindow", "INK 01 :"))
        self.label_3.setText(_translate("MainWindow", "INK 02 :"))
        self.label_4.setText(_translate("MainWindow", "INK 03 :"))
        self.label_5.setText(_translate("MainWindow", "INK 04 :"))
        self.label_6.setText(_translate("MainWindow", "Syringe Size"))
        self.label_7.setText(_translate("MainWindow", "Flow Rate"))
        self.inkmotorpushButton01Forward.setText(_translate("MainWindow", "Forward"))
        self.inkmotorpushButton02Forward.setText(_translate("MainWindow", "Forward"))
        self.inkmotorpushButton03Forward.setText(_translate("MainWindow", "Forward"))
        self.inkmotorpushButton04Forward.setText(_translate("MainWindow", "Forward"))
        self.inkmotorpushButton01Backward.setText(_translate("MainWindow", "Backward"))
        self.inkmotorpushButton02Backward.setText(_translate("MainWindow", "Backward"))
        self.inkmotorpushButton03Backward.setText(_translate("MainWindow", "Backward"))
        self.inkmotorpushButton03Backward_2.setText(_translate("MainWindow", "Backward"))
        self.inkmotorpushButton01Stop.setText(_translate("MainWindow", "STOP"))
        self.inkmotorpushButton02Stop.setText(_translate("MainWindow", "STOP"))
        self.inkmotorpushButton03Stop.setText(_translate("MainWindow", "STOP"))
        self.inkmotorpushButton04Stop.setText(_translate("MainWindow", "STOP"))
        self.startpushButton.setText(_translate("MainWindow", "Start"))
        self.stoppushButton.setText(_translate("MainWindow", "Stop"))
        self.movementspeedgroupBox.setTitle(_translate("MainWindow", "Movement Speed"))
        self.label_10.setText(_translate("MainWindow", "Coating Speed"))
        self.drivemotorforwardpushButton.setText(_translate("MainWindow", "Forward"))
        self.drivemotorbackwardpushButton.setText(_translate("MainWindow", "Backward"))
        self.drivemotorstoppushButton.setText(_translate("MainWindow", "Stop"))
        self.tempgroupBox.setTitle(_translate("MainWindow", "Bed Temperature"))
        self.label_11.setText(_translate("MainWindow", "Coater 01 :"))
        self.label_12.setText(_translate("MainWindow", "Coater 02 :"))
        self.label_13.setText(_translate("MainWindow", "Currunt temp"))
        self.label_14.setText(_translate("MainWindow", "°C"))
        self.label_15.setText(_translate("MainWindow", "°C"))
        self.label_16.setText(_translate("MainWindow", "°C"))
        self.livecamlabel.setText(_translate("MainWindow", "Live Camera"))
        self.currentstategroupBox.setTitle(_translate("MainWindow", "Coater Current State"))
        self.currentlabel01.setText(_translate("MainWindow", "Running"))
        self.currentlabel02.setText(_translate("MainWindow", "Pause"))
        self.groupBox.setTitle(_translate("MainWindow", "Air Temperature"))
        self.label.setText(_translate("MainWindow", "Air Heater"))
        self.label_17.setText(_translate("MainWindow", "°C"))
        self.label_18.setText(_translate("MainWindow", "Currunt temp"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Live Camara Config"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "STOP"))
        self.menuEdit.setTitle(_translate("MainWindow", "File"))
        self.actionopen.setText(_translate("MainWindow", "Open"))
        self.actionsave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionAdd_Ink.setText(_translate("MainWindow", "Add Ink"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
