# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoStream.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoStream(object):
    def setupUi(self, VideoStream):
        VideoStream.setObjectName("VideoStream")
        VideoStream.resize(400, 300)
        VideoStream.setStyleSheet("background-color: #3a4f6b;\n"
"")
        self.pushButtonOn = QtWidgets.QPushButton(VideoStream)
        self.pushButtonOn.setGeometry(QtCore.QRect(360, 10, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOn.sizePolicy().hasHeightForWidth())
        self.pushButtonOn.setSizePolicy(sizePolicy)
        self.pushButtonOn.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonOn.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid #ffffff;\n"
"    background-color: #33BF1B;\n"
"    background-position: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #40D627;\n"
"}\n"
"")
        self.pushButtonOn.setText("")
        self.pushButtonOn.setObjectName("pushButtonOn")
        self.pushButtonOff = QtWidgets.QPushButton(VideoStream)
        self.pushButtonOff.setGeometry(QtCore.QRect(360, 50, 30, 30))
        self.pushButtonOff.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid #ffffff;\n"
"    background-color: #F7421E;\n"
"    background-position: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F0583A;\n"
"}\n"
"")
        self.pushButtonOff.setText("")
        self.pushButtonOff.setObjectName("pushButtonOff")
        self.pushButtonFlash = QtWidgets.QPushButton(VideoStream)
        self.pushButtonFlash.setGeometry(QtCore.QRect(360, 90, 30, 30))
        self.pushButtonFlash.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border: 2px solid #fff;\n"
"    background-color: #F0F533;\n"
"    background-position: center;\n"
"    background-origin: content;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F9FF66;\n"
"}\n"
"")
        self.pushButtonFlash.setText("")
        self.pushButtonFlash.setObjectName("pushButtonFlash")
        self.labelCam = QtWidgets.QLabel(VideoStream)
        self.labelCam.setGeometry(QtCore.QRect(0, 0, 350, 300))
        self.labelCam.setStyleSheet("background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0   #2c3e50,\n"
"    stop:0.5 #34495e,\n"
"    stop:1   #3a4f6b\n"
");\n"
"")
        self.labelCam.setText("")
        self.labelCam.setObjectName("labelCam")

        self.retranslateUi(VideoStream)
        QtCore.QMetaObject.connectSlotsByName(VideoStream)

    def retranslateUi(self, VideoStream):
        _translate = QtCore.QCoreApplication.translate
        VideoStream.setWindowTitle(_translate("VideoStream", "VIdeoStream"))
